# .github/workflows/e2e.yml
name: E2E

on: [push, pull_request]

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      # ───────── Install ─────────
      - name: Install dependencies with pnpm
        run: pnpm install --no-frozen-lockfile

      # ───────── Build ─────────
      - name: Build project
        run: pnpm build

      # ───────── Serve in prod mode ─────────
      - name: Start production server in background
        run: pnpm start -p 3000 &
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          # …whatever else you need

      # Wait until server responds on port 3000
      - name: Wait for server to boot
        run: npx wait-on http://localhost:3000 --timeout 120000 # Added 2-minute timeout

      # ───────── Run E2E tests ─────────
      - name: Run E2E tests
        run: pnpm e2e:ci
