# .github/workflows/e2e.yml
name: E2E

on: [push, pull_request]

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4 # <-- CORRECTED INDENTATION HERE
        with:
          node-version: 18
          cache: 'pnpm'

      # Debugging steps (temporarily add these to confirm your path)
      # IMPORTANT: Check the output of these steps in your CI logs to find the correct 'working-directory' path.
      # The 'find' command will tell you the exact path to your pnpm-lock.yaml.
      - name: Show current working directory
        run: pwd
      - name: List files in current directory
        run: ls -la
      - name: Recursively list all pnpm-lock.yaml files
        run: find . -name "pnpm-lock.yaml"

      # ───────── Install ─────────
      - name: Install dependencies with pnpm (frozen)
        run: pnpm install --frozen-lockfile
        # <-- IMPORTANT: Replace './client' with the actual path to your project's root!
        # For example, if 'find' shows './frontend/pnpm-lock.yaml', use './frontend'.
        # If it shows './pnpm-lock.yaml', you can remove the 'working-directory' line or use '.'
        working-directory: ./client # <-- UPDATE THIS LINE

      # ───────── Build ─────────
      - name: Build project
        run: pnpm build
        # <-- IMPORTANT: Apply working-directory to all pnpm commands
        working-directory: ./client # <-- UPDATE THIS LINE

      # ───────── Serve in prod mode ─────────
      - name: Start production server in background
        run: pnpm start -p 3000 &
        # <-- IMPORTANT: Apply working-directory if 'start' is also in this dir
        working-directory: ./client # <-- UPDATE THIS LINE
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          # …whatever else you need

      # Wait until server responds on port 3000
      - name: Wait for server to boot
        run: npx wait-on http://localhost:3000

      # ───────── Run E2E tests ─────────
      - name: Run E2E tests
        run: pnpm e2e:ci
        # <-- IMPORTANT: Apply working-directory if 'e2e:ci' is also in this dir
        working-directory: ./client # <-- UPDATE THIS LINE
