name: Lighthouse CI

on:
  pull_request:
  push:
    branches: [main, dev]

jobs:
  lhci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ───────── pnpm + Node 18 ─────────
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      # Install deps (no strict lockfile check)
      - run: pnpm install --no-frozen-lockfile

      # Build the production bundle
      - run: pnpm build

      # Start Next in prod mode on port 3000 (background)
      - run: pnpm start -p 3000 &

      # ───────── Lighthouse CI ─────────
      - name: Run Lighthouse CI
        run: pnpm dlx @lhci/cli@0.13.x autorun --config=./lighthouserc.json
