name: Lighthouse CI

on:
  pull_request:
  push:
    branches: [main, dev]

jobs:
  lhci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # pnpm + Node
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      # ───────── Install ─────────
      - run: pnpm install --no-frozen-lockfile

      # ───────── Build ─────────
      - run: pnpm build

      # ───────── Serve in prod mode ─────────
      - name: Start Next server
        run: pnpm start -p 3000 &
        env:                    # ← dummy runtime secrets so Next/Fn don't 500
          DATABASE_URL: "postgresql://user:pw@localhost:5432/db"
          NEXTAUTH_SECRET: "ci-secret"
          RESEND_API_KEY: "dummy"
          GOOGLE_CLIENT_ID: "dummy"
          GOOGLE_CLIENT_SECRET: "dummy"

      # Wait until server responds on port 3000
      - run: npx wait-on http://localhost:3000 --timeout 60000

      # ───────── Lighthouse  ─────────
      - name: Run Lighthouse CI
        run: pnpm dlx @lhci/cli@0.13.x autorun --config=./lighthouserc.json
