name: Lighthouse CI

on:
  pull_request:
  push:
    branches: [main, dev]

jobs:
  lhci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up pnpm + Node 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install --no-frozen-lockfile
      - run: pnpm add -D @lhci/cli

      # Run LHCI with the config above
      - name: Run Lighthouse CI
        run: npx lhci autorun --config=./lighthouserc.json
